# Generated by Django 6.0.6 on 2026-06-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, unique=True)),
                ('hex_color', models.CharField(default='#10B981', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_hub.aimodel')),
            ],
        ),
    ]
