# Generated by Django 6.0.6 on 2026-06-18 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0002_annotationclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(default='yolo', max_length=10)),
                ('enable_crosshair', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
