# Generated by Django 6.0.6 on 2026-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0003_workspacepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacepreference',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacepreference',
            name='box_opacity',
            field=models.IntegerField(default=40),
        ),
    ]
