# Generated by Django 6.0.6 on 2026-06-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0004_workspacepreference_auto_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacepreference',
            name='export_format',
            field=models.CharField(default='yolo', max_length=50),
        ),
    ]
