# Generated by Django 6.0.6 on 2026-06-19 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0005_alter_workspacepreference_export_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_images', models.IntegerField(default=0)),
                ('train_split', models.IntegerField(default=80)),
                ('val_split', models.IntegerField(default=20)),
                ('yaml_file_path', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=16)),
                ('img_size', models.IntegerField(default=640)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_map_score', models.FloatField(blank=True, null=True)),
                ('weights_path', models.CharField(blank=True, max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.datasetversion')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
