# Generated by Django 6.0.6 on 2026-06-19 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0006_datasetversion_trainingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectresult',
            name='detected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
