# Generated by Django 6.0.6 on 2026-06-19 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0007_defectresult_detected_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJobRecord',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(default='Batch Upload', max_length=255)),
                ('total_images', models.IntegerField(default=0)),
                ('total_defects_found', models.IntegerField(default=0)),
                ('clean_boards', models.IntegerField(default=0)),
                ('defective_boards', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
