# Generated by Django 6.0.6 on 2026-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0008_batchjobrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjobrecord',
            name='defect_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
