# Generated by Django 6.0.6 on 2026-06-20 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0010_manualcorrection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
