# Generated by Django 6.0.6 on 2026-06-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0011_defectresult_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationclass',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
