# Generated by Django 6.0.6 on 2026-06-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0012_annotationclass_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationclass',
            name='created_by',
        ),
    ]
