# Generated by Django 6.0.6 on 2026-06-20 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0013_remove_annotationclass_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationclass',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
