# Generated by Django 6.0.6 on 2026-06-20 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0014_annotationclass_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
