# Generated by Django 6.0.6 on 2026-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0015_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='device',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='learning_rate',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='model_architecture',
            field=models.CharField(default='yolov8m.pt', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='patience',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='run_name',
            field=models.CharField(default='Unknown_Run', max_length=100),
        ),
    ]
