# Generated by Django 6.0.6 on 2026-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0016_trainingrun_device_trainingrun_learning_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='weight_decay',
            field=models.FloatField(default=0.0005),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='model_architecture',
            field=models.CharField(default='yolov8n.pt', max_length=50),
        ),
    ]
