# Generated by Django 6.0.6 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0017_trainingrun_weight_decay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='amp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='optimizer_strategy',
            field=models.CharField(default='AdamW', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='workers',
            field=models.IntegerField(default=8),
        ),
    ]
