# Generated by Django 6.0.6 on 2026-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0018_trainingrun_amp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='mixup',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='mosaic',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='warmup_epochs',
            field=models.FloatField(default=3.0),
        ),
    ]
