# Generated by Django 6.0.6 on 2026-06-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0019_trainingrun_mixup_trainingrun_mosaic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrun',
            name='amp_enabled',
        ),
        migrations.RemoveField(
            model_name='trainingrun',
            name='workers',
        ),
    ]
