# Generated by Django 6.0.6 on 2026-06-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0020_remove_trainingrun_amp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='degrees',
            field=models.FloatField(default=0.0),
        ),
    ]
