# Generated by Django 6.0.6 on 2026-06-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0021_trainingrun_degrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_name', models.CharField(default='Val_Run', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('map50', models.FloatField(blank=True, null=True)),
                ('map50_95', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.datasetversion')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.trainingrun')),
            ],
        ),
    ]
