# Generated by Django 6.0.6 on 2026-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0022_validationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='fn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='fp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='tn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='tp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
