# Generated by Django 6.0.6 on 2026-06-21 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0023_validationrun_fn_validationrun_fp_validationrun_tn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedModel',
            fields=[
                ('deployment_id', models.AutoField(primary_key=True, serialize=False)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deployed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('training_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_hub.trainingrun')),
            ],
        ),
    ]
