# Generated by Django 6.0.6 on 2026-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0024_deployedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='class_names',
            field=models.JSONField(default=list),
        ),
    ]
